CREATE DATASET AND LOAD DATASET

Ashman V. Aiyer

ENTC-A2

PRN: 25070123025

In [ ]:
#Dataset Creation
import pandas as pd
data={
    "Roll_No":[101,102,103,104,105],
    "Gender":["Female","Male","Female","Male","Female"],
    "Department":["Computer","IT","ENTC","Mechanical","Computer"],
    "CGPA":[8.2,7.5,9.1,6.8,8.7],
    "Year":[1,3,2,4,1],
}
df=pd.DataFrame(data)
df.to_csv("student_data.csv",index=False)
df

   Roll_No  Gender  Department  CGPA  Year
0      101  Female    Computer   8.2     1
1      102    Male          IT   7.5     3
2      103  Female        ENTC   9.1     2
3      104    Male  Mechanical   6.8     4
4      105  Female    Computer   8.7     1

In [ ]:
df.shape

(5, 5)

In [ ]:
df.size

25

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No     5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
 4   Year        5 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes

In [ ]:
df.describe()

          Roll_No     CGPA     Year
count    5.000000  5.00000  5.00000
mean   103.000000  8.06000  2.20000
std      1.581139  0.92358  1.30384
min    101.000000  6.80000  1.00000
25%    102.000000  7.50000  1.00000
50%    103.000000  8.20000  2.00000
75%    104.000000  8.70000  3.00000
max    105.000000  9.10000  4.00000

In [ ]:
#Access information of Column Department
df["Department"]

0      Computer
1            IT
2          ENTC
3    Mechanical
4      Computer
Name: Department, dtype: object

In [ ]:
#Access Information of PRN 103
df[df["Roll_No"]==103]

   Roll_No  Gender Department  CGPA  Year
2      103  Female       ENTC   9.1     2

In [ ]:
#Find out data type of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No     5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
 4   Year        5 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes

In [ ]:
#Perform mean,median,mode operation
print(df['CGPA'].mean())
print(df['CGPA'].median())
print(df['CGPA'].mode())

8.059999999999999
8.2
0    6.8
1    7.5
2    8.2
3    8.7
4    9.1
Name: CGPA, dtype: float64

In [ ]:
#Insert a new column Grade
df.insert('Grade',)

In [ ]:
#Upload the dataset
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,Front,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,NaN,Front,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,NaN,Front,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,NaN,Front,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,Rear,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,Front,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

In [ ]:
df.shape

(93, 27)

In [ ]:
df.size

2511

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Manufacturer        93 non-null     object
 1   Model               93 non-null     object
 2   Type                93 non-null     object
 3   Min.Price           93 non-null     float64
 4   Price               93 non-null     float64
 5   Max.Price           93 non-null     float64
 6   MPG.city            93 non-null     int64
 7   MPG.highway         93 non-null     int64
 8   AirBags             59 non-null     object
 9   DriveTrain          93 non-null     object
 10  Cylinders           93 non-null     object
 11  EngineSize          93 non-null     float64
 12  Horsepower          93 non-null     int64
 13  RPM                 93 non-null     int64
 14  Rev.per.mile        93 non-null     int64
 15  Man.trans.avail     93 non-null     object
 16  Fuel.tank.capacity  93 non-null     float64
 17  Passengers          93 non-null     int64
 18  Length              93 non-null     int64
 19  Wheelbase           93 non-null     int64
 20  Width               93 non-null     int64
 21  Turn.circle         93 non-null     int64
 22  Rear.seat.room      91 non-null     float64
 23  Luggage.room        82 non-null     float64
 24  Weight              93 non-null     int64
 25  Origin              93 non-null     object
 26  Make                93 non-null     object
dtypes: float64(7), int64(11), object(9)
memory usage: 19.7+ KB

In [ ]:
df.describe()

,Min.Price,Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight
count,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000,93.000000
mean,17.125806,19.509677,21.898925,22.365591,29.086022,2.667742,143.827957,5280.645161,2332.204301,16.664516,5.086022,183.204301,103.946237,69.376344,38.956989,27.829670,13.890244,3072.903226
std,8.746029,9.659430,11.030457,5.619812,5.331726,1.037363,52.374410,596.731690,496.506525,3.279370,1.038979,14.602382,6.819674,3.778986,3.223265,2.989072,2.997967,589.896510
min,6.700000,7.400000,7.900000,15.000000,20.000000,1.000000,55.000000,3800.000000,1320.000000,9.200000,2.000000,141.000000,90.000000,60.000000,32.000000,19.000000,6.000000,1695.000000
25%,10.800000,12.200000,14.700000,18.000000,26.000000,1.800000,103.000000,4800.000000,1985.000000,14.500000,4.000000,174.000000,98.000000,67.000000,37.000000,26.000000,12.000000,2620.000000
50%,14.700000,17.700000,19.600000,21.000000,28.000000,2.400000,140.000000,5200.000000,2340.000000,16.400000,5.000000,183.000000,103.000000,69.000000,39.000000,27.500000,14.000000,3040.000000
75%,20.300000,23.300000,25.300000,25.000000,31.000000,3.300000,170.000000,5750.000000,2565.000000,18.800000,6.000000,192.000000,110.000000,72.000000,41.000000,30.000000,15.000000,3525.000000
max,45.400000,61.900000,80.000000,46.000000,50.000000,5.700000,300.000000,6500.000000,3755.000000,27.000000,8.000000,219.000000,119.000000,78.000000,45.000000,36.000000,22.000000,4105.000000